// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe-V37eomzuq-oIYhXHr1Bcu1Nm8wQ5vs',
    appId: '1:283870732103:android:587778bb4ecd309f707662',
    messagingSenderId: '283870732103',
    projectId: 'ni-coaching-app-2025',
    storageBucket: 'ni-coaching-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC-7cOTTKr7Y2QkN6UCsTbFsBe9l7RHT0',
    appId: '1:283870732103:ios:f121d9352edff6a8707662',
    messagingSenderId: '283870732103',
    projectId: 'ni-coaching-app-2025',
    storageBucket: 'ni-coaching-app-2025.firebasestorage.app',
    iosBundleId: 'com.nurturinginstitute.ni',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIwXlcsimbpX0vR7NZCJYRnq0g1_N8RKQ',
    appId: '1:283870732103:web:be142f01a2c0ec35707662',
    messagingSenderId: '283870732103',
    projectId: 'ni-coaching-app-2025',
    authDomain: 'ni-coaching-app-2025.firebaseapp.com',
    storageBucket: 'ni-coaching-app-2025.firebasestorage.app',
    measurementId: 'G-FJ1593C3WS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC-7cOTTKr7Y2QkN6UCsTbFsBe9l7RHT0',
    appId: '1:283870732103:ios:d8735637abe54c34707662',
    messagingSenderId: '283870732103',
    projectId: 'ni-coaching-app-2025',
    storageBucket: 'ni-coaching-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.nurturingInstituteMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIwXlcsimbpX0vR7NZCJYRnq0g1_N8RKQ',
    appId: '1:283870732103:web:fbb827387fde73e5707662',
    messagingSenderId: '283870732103',
    projectId: 'ni-coaching-app-2025',
    authDomain: 'ni-coaching-app-2025.firebaseapp.com',
    storageBucket: 'ni-coaching-app-2025.firebasestorage.app',
    measurementId: 'G-HKN87L4910',
  );

}