// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DevFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DevFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYPF7eIh8jrbr6OO6qHlag8hwcdAu9LZw',
    appId: '1:106429952321:android:0da7c57ecd064f060df1c0',
    messagingSenderId: '106429952321',
    projectId: 'test-db-ni-admin',
    storageBucket: 'test-db-ni-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4JxA6So_4exI_fvZLrcvWlrEkfaPcl48',
    appId: '1:106429952321:ios:fb0ea25b7e5e72690df1c0',
    messagingSenderId: '106429952321',
    projectId: 'test-db-ni-admin',
    storageBucket: 'test-db-ni-admin.firebasestorage.app',
    iosBundleId: 'com.nurturinginstitute.ni',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnYhYin06mdaTyU1ZOlwwYHBt6xUpTlog',
    appId: '1:106429952321:web:a60a627cf8e24f250df1c0',
    messagingSenderId: '106429952321',
    projectId: 'test-db-ni-admin',
    authDomain: 'test-db-ni-admin.firebaseapp.com',
    storageBucket: 'test-db-ni-admin.firebasestorage.app',
    measurementId: 'G-WDN12FTQ84',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4JxA6So_4exI_fvZLrcvWlrEkfaPcl48',
    appId: '1:106429952321:ios:4d2563630acc2a0a0df1c0',
    messagingSenderId: '106429952321',
    projectId: 'test-db-ni-admin',
    storageBucket: 'test-db-ni-admin.firebasestorage.app',
    iosBundleId: 'com.example.nurturingInstituteMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnYhYin06mdaTyU1ZOlwwYHBt6xUpTlog',
    appId: '1:106429952321:web:a8232a30bf6e785d0df1c0',
    messagingSenderId: '106429952321',
    projectId: 'test-db-ni-admin',
    authDomain: 'test-db-ni-admin.firebaseapp.com',
    storageBucket: 'test-db-ni-admin.firebasestorage.app',
    measurementId: 'G-W414WQMF0G',
  );

}